### ISSUE TITLE
Can't retrieve config values from a mutli-dimensional JSON array.

### ISSUE THREAD

**Issue by ezrarieben** [mzdr/micro#1]
When loading a multi dimensional JSON array using the `config()->append()` function the `config()->get()` function is only able to return the first config index defined in the file. Any 2nd or 3d dimension indexes do not return the expected value. (NULL is returned).

**Example**
*Config:*
`{
  "foo": {
    "bar": "foobar"
  }}`

*Retrieving config item:*
`config()->get('foo.bar')`

*Returns:*
NULL

**Comment by ezrarieben** [comment]
This concerns micro v2.1.x installed via Composer

**Comment by mzdr** [comment]
Hey @ezrarieben,

thanks for using micro and reporting this issue. I’ve just fixed it and will release (v2.1.1) it on composer. Please give it a try and don’t hestitate to reopen this issue if the problem still persists. ✌️
